version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flask
    environment:
      - PORT=5000
      - MONGO_HOST=db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: python3 -u app.py

  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: