kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  config.yml: |-
    global:
      slack_api_url: 'https://hooks.slack.com/services/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'

    route:
      receiver: 'slack-notifications'

    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - channel: '#project'
        send_resolved: true
